name: lectura
description: A new Flutter project.

publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.6.2 # Keep the existing version for stability
  http: ^1.2.2 # Required for PayPal API integration
  path_provider: ^2.0.15
  open_filex: ^4.6.0 # Update to resolvable version
  async: ^2.11.0
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.18.0
  http_parser: ^4.0.2 # Downgraded for compatibility
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.0
  string_scanner: ^1.2.0
  app_links: ^6.3.3 # Stay with this version unless breaking changes are resolved
  url_launcher: ^6.1.11
  in_app_purchase: ^3.0.6 # Google Play Billing integration
  flutter_dotenv: ^5.0.2 # Added for managing environment variables securely

dev_dependencies:
  flutter_test:
    sdk: flutter
  boolean_selector: ^2.1.1
  fake_async: ^1.3.1
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  matcher: ^0.12.16+1
  stack_trace: ^1.11.1
  test_api: ^0.7.2
  vm_service: ^14.2.5 # Keep downgraded version for compatibility

flutter:
  uses-material-design: true
