name: lectura
description: A next-gen app for live transcription and smart exports.
publish_to: 'none'
version: 1.0.3+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Core Functionality
  speech_to_text: ^6.6.2
  http: ^1.2.2
  in_app_purchase: ^3.0.9
  url_launcher: ^6.3.1

  # File Handling
  path_provider: ^2.0.15
  open_filex: ^4.7.0
  pdf: ^3.10.8
  docx_template: ^0.4.0

  # Utilities
  flutter_dotenv: ^5.1.0
  logger: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/lectura_app_logo_512x512_transparent.png
    - assets/empty.docx
    - assets/template.docx
    - .env


